#!/bin/bash
set -e

cat <<EOF
#================================================================================
#================================================================================
# JJOB_DA_LETKF
# Run UMD-LETKF (Recenter and Remapping)
#================================================================================
#================================================================================
EOF

module purge
source $MOD_PATH/godas.main
module list

echo
echo "The system runs at $RUNCDATE"
echo
echo "The LETKF directory is " ${LETKFDIR}

cd ${LETKFDIR}

cat <<EOF
#============================================
# Run UMD-LETKF
#============================================
EOF

if [ -f "${LETKFDIR}/soca_gridspec.nc" ]; then
    echo
    echo 'SOCA grid exist, by-passing grid generation.'
    echo
else
    echo
    echo 'No grid found. Generating SOCA grid.'
    echo
    srun -n $NPE ${SOCA_EXEC}/soca_gridgen.x ${LETKFDIR}/yaml/gridgen.yml
fi

if [ -f "${ROOT_GODAS_DIR}/build/letkf/bin/letkfdriver" ]; then
 
    srun -n $NPE ${ROOT_GODAS_DIR}/build/letkf/bin/letkfdriver ${LETKFDIR}/yaml/letkf.yaml

else
    echo
    echo 'letkfdriver does not exist.'
    echo
fi

#cat <<EOF
##============================================
## Run Recenter
##============================================
#EOF

if [ ! -d RESTART ]; then mkdir -p RESTART; fi

export ENSEND=$((NMEM_PGRP * ENSGRP))
export ENSBEG=$((ENSEND - NMEM_PGRP + 1))

mv ocn.ana.*.nc ./Data

for MEMBER_NO in $(seq $ENSBEG $ENSEND); do
   echo
   echo Running Checkpoint for the $MEMBER_NO

   srun -n $NPE ${SOCA_EXEC}/soca_checkpoint_model.x ./yaml/checkpointmodel$MEMBER_NO.yml

   # TODO: The ice is not pertubated but eventually, it will.                                      
   # ciceprep_func "${RUNCDATE}/Data/cic.pert.ens.*.nc"                                            

   mkdir -p ${LETKFDIR}/mem$MEMBER_NO

   mv -f RESTART/* ${LETKFDIR}/mem$MEMBER_NO
   ln -s ${LETKFDIR}/mem$MEMBER_NO/MOM.res.nc ocn.ana.$MEMBER_NO.nc
done

srun -n $NPE ${SOCA_EXEC}/soca_ensrecenter.x ./yaml/ensrecenter.yml
